nobinobi_observation/urls.py
# -*- coding: utf-8 -*-
#  Copyright (c) 2021 <Florian Alu - alu@prolibre.com - https://www.prolibre.com>
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.urls import path, include

from nobinobi_observation import views

app_name = 'nobinobi_observation'
urlpatterns = [
    path(
        'api/observation/<uuid:child_pk>/',
        views.ObservationViewSet.as_view({'get': 'list'}),
        name='api-observation'
    ),
    path("observation/", include([
        path("observation/", include([
            path("",
                 view=views.ObservationListView.as_view(),
                 name='Observation_list',
                 ),
            path("~create/",
                 view=views.ObservationCreateView.as_view(),
                 name='Observation_create',
                 ),
            path("~choice/",
                 view=views.ObservationChoiceView.as_view(),
                 name='Observation_choice',
                 ),
            path("child/<uuid:pk>/",
                 view=views.ObservationDetailListView.as_view(),
                 name='Observation_detail_list',
                 ),
            path("<int:pk>/", include([
                path("",
                     view=views.ObservationDetailView.as_view(),
                     name='Observation_detail', ),
                path("~delete/",
                     view=views.ObservationDeleteView.as_view(),
                     name='Observation_delete', ),
                path("~update/",
                     view=views.ObservationUpdateView.as_view(),
                     name='Observation_update',
                     ),
            ])),
        ]))
    ]))
]

nobinobi_observation/models.py
# -*- coding: utf-8 -*-
#  Copyright (c) 2021 <Florian Alu - alu@prolibre.com - https://www.prolibre.com>
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.db import models
from django.utils.translation import gettext as _
from model_utils import Choices
from model_utils.fields import SplitField
from model_utils.models import TimeStampedModel, StatusModel
from nobinobi_child.models import Child
from nobinobi_staff.models import Staff


class Observation(StatusModel, TimeStampedModel):
    """Model for store observation child"""
    STATUS = Choices(
        ("very_good", "miao.png"),
        ("good", "smile.png"),
        ("bad", "spook.png"),
    )
    staff = models.ForeignKey(
        verbose_name=_("Staff"),
        to=Staff,
        on_delete=models.SET_NULL,
        related_name="observation_staff",
        blank=False,
        null=True,
    )

    child = models.ForeignKey(
        verbose_name=_("Child"),
        to=Child,
        on_delete=models.CASCADE,
    )
    date = models.DateTimeField(_("Date"))
    comment = SplitField(_("Comment"), help_text=_(
        "Looks for the marker &lt;!-- split --&gt; alone on a line "
        "and takes everything before that marker as the excerpt.<br>"
        " If no marker is found in the content, the first two paragraphs "
        "(where paragraphs are blocks of text separated by a blank line) are taken to be the excerpt."))

    class Meta:
        ordering = ('date', 'status',)
        unique_together = ('staff', 'child', 'date')
        verbose_name = _('Observation')
        verbose_name_plural = _('Observations')

    def __str__(self):
        return "{} - {} - {} - {}".format(
            self.child.full_name,
            self.STATUS[self.status],
            self.staff.full_name if self.staff else "",
            self.date
        )

nobinobi_observation/test_utils/test_app/models.py
# from django.db import models

# Put your test models here

nobinobi_observation/forms.py
#  Copyright (c) 2021 <Florian Alu - alu@prolibre.com - https://www.prolibre.com>
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from bootstrap_modal_forms.forms import BSModalModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from django import forms
from django.utils.translation import gettext as _
from django_select2.forms import ModelSelect2Widget
from nobinobi_child.models import Child
from nobinobi_core.widgets import InlineRadiosImage
from nobinobi_staff.models import Staff

from nobinobi_observation.models import Observation


class ObservationCreateForm(forms.ModelForm):
    child = forms.ModelChoiceField(
        label=_("Child"), queryset=Child.objects.filter(status=Child.STATUS.in_progress),
        widget=ModelSelect2Widget(
            model=Child,
            queryset=Child.objects.filter(status=Child.STATUS.in_progress),
            search_fields=['first_name__icontains', 'last_name__icontains']
        )
    )
    staff = forms.ModelChoiceField(
        label=_("Staff"),
        queryset=Staff.objects.filter(status=Staff.STATUS.active),
        widget=ModelSelect2Widget(
            model=Staff,
            queryset=Staff.objects.filter(status=Staff.STATUS.active),
            search_fields=['first_name__icontains', 'last_name__icontains']
        )
    )

    # date = forms.SplitDateTimeField(label=_("Date"), widget=widgets.AdminSplitDateTime(),)

    class Meta:
        model = Observation
        fields = ('status', "child", "date", "staff", "comment")
        widgets = {
            "date": DateTimePickerInput(
                options={
                    "locale": "fr",
                    "format": "DD/MM/YYYY HH:MM"
                }),
            "comment": forms.Textarea
        }

    def __init__(self, request=None, *args, **kwargs):
        super(ObservationCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        # self.helper.form_show_labels = False
        self.helper.form_tag = True
        self.helper.layout = Layout(
            # Div(
            Field("child", wrapper_class="col-sm-12 col-md-6"),
            Field("staff", wrapper_class="col-sm-12 col-md-6"),
            # css_class="row"
            # ),
            # Div(
            Field("date", wrapper_class="col-sm-12 col-md-6"),
            InlineRadiosImage("status", wrapper_class="col-sm-12 col-md-6"),
            # css_class="row"
            # ),
            Field("comment"),
        )
        self.helper.add_input(Submit("submit", _("Create")))


class ObservationUpdateForm(BSModalModelForm):
    staff = forms.ModelChoiceField(
        label=_("Staff"),
        queryset=Staff.objects.filter(status=Staff.STATUS.active),
        widget=ModelSelect2Widget(
            model=Staff,
            queryset=Staff.objects.filter(status=Staff.STATUS.active),
            search_fields=['first_name__icontains', 'last_name__icontains']
        )
    )

    class Meta:
        model = Observation
        fields = ('status', "date", "staff", "comment")
        widgets = {
            "date": DateTimePickerInput(
                options={
                    "locale": "fr",
                    "format": "DD/MM/YYYY HH:MM"
                })
        }


class ObservationChoiceForm(forms.Form):
    child = forms.ModelChoiceField(
        label=_("Child"),
        queryset=Child.objects.filter(status=Child.STATUS.in_progress),
        widget=ModelSelect2Widget(
            model=Child,
            queryset=Child.objects.filter(status=Child.STATUS.in_progress),
            search_fields=['first_name__icontains', 'last_name__icontains']
        )
    )

    def __init__(self, request=None, *args, **kwargs):
        super(ObservationChoiceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_show_labels = False
        self.helper.form_tag = True
        # self.helper.layout = Layout(        )
        self.helper.add_input(Submit("submit", _("Submit")))

nobinobi_observation/views.py
# -*- coding: utf-8 -*-
#  Copyright (c) 2021 <Florian Alu - alu@prolibre.com - https://www.prolibre.com>
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU Affero General Public License as
#      published by the Free Software Foundation, either version 3 of the
#      License, or any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU Affero General Public License for more details.
#
#      You should have received a copy of the GNU Affero General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from bootstrap_modal_forms.generic import BSModalReadView, BSModalDeleteView, BSModalUpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import (
    CreateView,
    ListView,
    FormView, TemplateView)
from nobinobi_child.models import Child
from rest_framework import viewsets

from nobinobi_observation.forms import ObservationCreateForm, ObservationChoiceForm, ObservationUpdateForm
from nobinobi_observation.models import Observation
from nobinobi_observation.serializers import ObservationSerializer


class ObservationViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = ObservationSerializer

    def get_queryset(self):
        return Observation.objects.filter(child_id=self.kwargs.get("child_pk")).order_by("-date")


class ObservationCreateView(LoginRequiredMixin, CreateView):
    model = Observation
    form_class = ObservationCreateForm

    def form_valid(self, form):
        pk = form.cleaned_data['child'].pk
        self.object = form.save()
        return HttpResponseRedirect(reverse("nobinobi_observation:Observation_detail_list", kwargs={"pk": pk}))


class ObservationDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Observation
    template_name = 'nobinobi_observation/observation_confirm_delete.html'
    success_message = _("The observation was successfully deleted.")

    def get_success_url(self):
        return reverse("nobinobi_observation:Observation_detail_list", kwargs={"pk": self.object.child.pk})


class ObservationDetailView(LoginRequiredMixin, BSModalReadView):
    model = Observation
    template_name = 'nobinobi_observation/observation_detail.html'


class ObservationUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Observation
    form_class = ObservationUpdateForm
    template_name = 'nobinobi_observation/observation_update.html'
    success_message = _("The observation was successfully updated.")

    def get_success_url(self):
        return reverse("nobinobi_observation:Observation_detail_list", kwargs={"pk": self.object.child.pk})


class ObservationListView(LoginRequiredMixin, ListView):
    model = Observation


class ObservationDetailListView(LoginRequiredMixin, TemplateView):
    template_name = "nobinobi_observation/observation_detail_list.html"

    def get_context_data(self, **kwargs):
        context = super(ObservationDetailListView, self).get_context_data(**kwargs)
        context['title'] = _("List of observations")
        context['child'] = get_object_or_404(Child, pk=kwargs["pk"])
        context['observation_list'] = Observation.objects.filter(child=kwargs["pk"])
        return context


class ObservationChoiceView(LoginRequiredMixin, FormView):
    form_class = ObservationChoiceForm
    template_name = "nobinobi_observation/observation_choice.html"

    def form_valid(self, form):
        pk = form.cleaned_data['child'].pk
        return HttpResponseRedirect(reverse("nobinobi_observation:Observation_detail_list", kwargs={"pk": pk}))

nobinobi_observation/templates/nobinobi_observation/observation_choice.html
{% extends "nobinobi_child/base.html" %}
{% load i18n crispy_forms_tags %}


{% block title %}{% trans "Choice a child" %} - {% trans "List of observations" %}{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  <li class="breadcrumb-item">{% trans "Observation" %}</li>
  <li class="breadcrumb-item">{% trans "List of observations" %}</li>
  <li class="breadcrumb-item active">{% trans "Choice a child" %}</li>
{% endblock %}

{% block content_title %}
  {% trans "List of observations" %}
{% endblock %}
{% block content_card_title %}{% trans "Choice a child" %}{% endblock %}
{% block content_card_body %}
  {% crispy form form.helper %}
{% endblock %}
{% block content_card_footer %}

{% endblock %}

nobinobi_observation/templates/nobinobi_observation/observation_confirm_delete.html
{% load widget_tweaks i18n %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{% trans "Delete Observation" %}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>{% blocktrans %}Are you sure you want to delete observation:{% endblocktrans %} <strong>{{ observation.date|date:"SHORT_DATETIME_FORMAT" }} </strong> {% trans "for child"%} <strong>{{ observation.child.full_name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
  </div>

</form>

nobinobi_observation/templates/nobinobi_observation/observation_detail.html
{% load static i18n %}

<div class="modal-header">
  <h3 class="modal-title">{% trans "Observation detail" %}</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <div class="card">
    <div class="card-header">
      <h2>{{ object.child }} <span class="badge"><img src="{% static "img/smiley/" %}{{ object.get_status_display }}" alt="{{ object.status }}" width="50px"></span></h2>
    </div>
    <div class="card-body">
      <p class="card-text">{{ object.comment|linebreaksbr }}</p>
    </div>
    <div class="card-footer text-muted">{{ object.date|date:"SHORT_DATETIME_FORMAT" }} {% trans "by" %} {{ object.staff.full_name }}</div>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
</div>

nobinobi_observation/templates/nobinobi_observation/observation_detail_list.html
<!--
  ~   Copyright (C) Prolibre Sarl 2019 <Florian Alu> <alu@prolibre.com>
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU Affero General Public License as
  ~     published by the Free Software Foundation, either version 3 of the
  ~     License and any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU Affero General Public License for more details.
  ~
  ~     You should have received a copy of the GNU Affero General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->
{% extends "nobinobi_child/base.html" %}
{% load i18n static %}

{% block title %}{{ child.full_name }} - {{ title }}{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/DataTables/datatables.min.css' %}"/>
  <style>
    .img-container {
    {#width: 150px;#}{#height: 225px;#} position: relative;
      display: inline-block;
    {#margin: 10px 5px 5px;#}
    }

    .img-text {
      text-align: center;
      bottom: 2%;
      left: 0;
      right: 0;
      height: 30px;
      position: absolute;
      background-color: white;
      opacity: 0.85;
      display: block;
    }

    .border-gray {
      border-color: #adb5bd !important;
    }

    .btn-group-xs > .btn, .btn-xs {
      padding: .25rem .4rem;
      font-size: .875rem;
      line-height: .5;
      border-radius: .2rem;
    }

    .modal-backdrop {
      z-index: auto;
    }

  </style>
{% endblock %}

{% block content_title_block %}
  <h1>{{ title }} - {{ child.full_name }}</h1>
{% endblock %}

{% block breadcrumb %}
	{{ block.super }}
  <li class="breadcrumb-item">{% trans "Observation" %}</li>
  <li class="breadcrumb-item">{{ child.full_name }}</li>
  <li class="breadcrumb-item active">{{ title }}</li>
{% endblock %}


{% block content_card %}
	{% include "includes/messages.html" %}
  <div class="card-body">
    <table id="child_datatables" class="display table mt- table-bordered table-condensed" style="width:100%">
      <thead>
      <tr>
        <th width="20%">{% trans "date" %}</th>
        <th width="15%">{% trans "staff" %}</th>
        <th width="10%">{% trans "status" %}</th>
        <th width="50%">{% trans "excerpt" %}</th>
        <th width="5%">{% trans "Actions" %}</th>

      </tr>
      </thead>
    </table>
  </div>
	<!-- modal instanstiation -->
	{% include "includes/modal.html" %}
{% endblock %}

{% block extrajs %}
  <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
  <script src="{% static 'vendor/DataTables/datatables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/moment-with-locales.min.js' %}"></script>
	{#  <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>#}
  <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
  <script>
      let table = null;
      $(document).ready(function () {
          table = $('#child_datatables').DataTable({
              "language": {
                  "url": "{% static 'vendor/DataTables/DataTables-1.10.18/i18n/French.json' %}"
              },
              "processing": true,
              "serverSide": true,
              "ajax": {
                  url: "{% url 'nobinobi_observation:api-observation' child_pk=child.pk %}?format=datatables",
              },
              "order": [[0, "desc"]],
              "columns": [
                  {
                      data: "date",
                      name: "date",
                      render: function (row, index, datatable) {
                          moment.locale("fr");         // en
                          let date = moment(row);
                          return date.format('lll');
                      },
                  },
                  {
                      data: "staff",
                      name: "staff__first_name, staff__last_name",
                      render: function (row, index, datatable) {
                          if (row == null || row === 'undefined'){
                            return "{% trans "Empty" %}";
                          } else {
                              return row.first_name + " " + row.last_name;
                          }
                      },
                  },
                  {
                      data: "status",
                      name: "status",
                      render: function (row, index, datatable) {
                          return '<img width="30px "src="{% static "img/smiley" %}/' + row + '" alt="' + row + '">';
                      },
                  },
                  {
                      data: "_comment_excerpt",
                      name: "_comment_excerpt",
                      render: function (row, index, data) {
                          return row.replace("\n\n", "<br><br>").replace("\n", "<br>");
                      },
                  },
                  {
                      data: null,
                      orderable: false,
                      searchable: false,
                      render: function (row, index, datatable) {
                          return '<div class="btn-group">' +
                              '{% if perms.nobinobi_observation.view_observation %}' +
                                  '<button data-id="{% url "nobinobi_observation:Observation_detail" pk=123 %}" class="observation-detail btn btn-info"><i class="fa fa-eye"></i></button>'.replace(123, datatable.id)
                                  +
                                  '{% endif %}' +
                              '{% if perms.nobinobi_observation.change_observation %}' +
                                  '<button data-id="{% url "nobinobi_observation:Observation_update" pk=123 %}" class="observation-update btn btn-primary"><i class="fa fa-edit"></i></button>'.replace(123, datatable.id)
                                  +
                                  '{% endif %}' +
                              '{% if perms.nobinobi_observation.delete_observation %}' +
                                  '<button data-id="{% url "nobinobi_observation:Observation_delete" pk=123 %}" class="observation-delete btn btn-danger"><i class="fa fa-times"></i></button>'.replace(123, datatable.id)
                                  +
                                  '{% endif %}' +
                              '</div>';
                      },
                  },

              ],
              dom: 'Bfrtip',
              buttons:
                  [
                      'print',
                      'csvHtml5',
                      'pdfHtml5',
                  ],
              responsive:
                  true,
              {#"searchCols": [#}
              {#  {"search": 'in_progress'},#}
              {#],#}
          });
          table.on('draw', function () {
              create_event_button();
          });
          table.on('responsive-display', function (e, datatable, row, showHide, update) {
              create_event_button();
          });
      });

      function create_event_button() {
          // Update observation buttons
          $(".observation-update").each(function () {
              $(this).modalForm({formURL: $(this).data('id')});
          });

          // Read observation buttons
          $(".observation-detail").each(function () {
              $(this).modalForm({formURL: $(this).data('id')});
          });

          // Delete observation buttons
          $(".observation-delete").each(function () {
              $(this).modalForm({formURL: $(this).data('id')});
          });
      }

  </script>
{% endblock %}

nobinobi_observation/templates/nobinobi_observation/observation_form.html
{% extends "nobinobi_child/base.html" %}
{% load i18n crispy_forms_tags static %}


{% block title %}{% trans "Create Observation" %}{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  <li class="breadcrumb-item">{% trans "Observation" %}</li>
  <li class="breadcrumb-item">{% trans "Create Observation" %}</li>
  <li class="breadcrumb-item active">{% trans "Choice a child" %}</li>
{% endblock %}

{% block content_title %}
  {% trans "Create Observation" %}
{% endblock %}
{% block content_card_title %}

{% endblock %}
{% block content_card_body %}
  {% crispy form form.helper %}
{% endblock %}
{% block content_card_footer %}

{% endblock %}

{% block extrajs %}
  <script type="text/javascript" src="{% static 'js/moment-with-locales.min.js' %}"></script>{% endblock %}

nobinobi_observation/templates/nobinobi_observation/observation_list.html
{% extends "nobinobi_child/base.html" %}
{% load i18n crispy_forms_tags %}

{% block content_title %}
  {% trans "Observation list" %}
{% endblock %}
{% block content_card_title %}

{% endblock %}
{% block content_card_body %}

{% endblock %}
{% block content_card_footer %}

{% endblock %}

nobinobi_observation/templates/nobinobi_observation/observation_update.html
{% load i18n %}
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}
    {{ form.media }}
    <div class="modal-header">
        <h3 class="modal-title">{% trans "Update Observation" %}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.field.required %}
                    {% render_field field required="required" class="form-control" placeholder=field.label %}
                {% else %}
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="submit" class="submit-btn btn btn-primary">{% trans "Update" %}</button>
    </div>
</form>